/**
 * AI Insights Daily - Main Page Component
 * 
 * This is the primary page component for the AI Insights Daily website.
 * It displays a chronological feed of daily AI tools and news updates,
 * automatically generated from the backend discovery system.
 * 
 * Key Features:
 * - Responsive design with dark/light mode support
 * - Chronological display of daily updates
 * - Automatic grouping of news and tools by date
 * - Collapsible sections for better UX
 * - SEO-optimized structure
 * 
 * The component processes content from the data/content.ts file,
 * which is automatically generated by the Python backend scripts.
 * 
 * Author: AI Insights Daily Team
 * Version: 3.1.0
 * Last Updated: June 2025
 */

import { content } from '@/data/content';
import { Inter } from "next/font/google";
import { DailyUpdateSection } from '@/components/DailyUpdateSection';

// Configure Inter font for optimal typography
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // Extract daily updates from the content data
  // This data is automatically generated by the Python backend
  const { daily_updates } = content;

  /**
   * Group all updates by date for better organization and display
   * 
   * This function processes the raw daily updates and groups them
   * by date, separating news and tools into their respective arrays.
   * This allows for cleaner rendering and better user experience.
   * 
   * The grouping uses JavaScript's toDateString() method for consistent
   * date formatting across different browsers and timezones.
   */
  const updatesByDate = daily_updates.reduce((acc, update) => {
    // Create a clean date key for grouping (e.g., "Fri Jun 20 2025")
    const dateKey = new Date(update.date).toDateString();
    
    // Initialize the date group if it doesn't exist
    if (!acc[dateKey]) {
      acc[dateKey] = { date: update.date, news: [], tools: [] };
    }
    
    // Categorize the update data based on its type
    if (update.type === 'news') {
      acc[dateKey].news.push(...update.data);
    } else if (update.type === 'tools') {
      acc[dateKey].tools.push(...update.data);
    }
    
    return acc;
  }, {} as Record<string, { date: string; news: any[]; tools: any[] }>);

  /**
   * Convert grouped updates back to a sorted array for rendering
   * 
   * This step converts the grouped object back into an array and
   * sorts it by date (newest first) for proper chronological display.
   * The sorting ensures users see the most recent content first.
   */
  const sortedDailyUpdates = Object.values(updatesByDate)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <main
      className={`min-h-screen bg-slate-100 dark:bg-slate-950 text-slate-800 dark:text-slate-200 flex flex-col items-center p-4 sm:p-6 md:p-8 ${inter.className}`}
    >
      <div className="max-w-4xl w-full">
        {/* 
          Header Section
          Contains the main title and description of the website.
          Uses responsive typography and proper semantic structure.
        */}
        <header className="text-center my-12 md:my-16">
          <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight text-slate-900 dark:text-slate-100">
            AI Insights Daily
          </h1>
          <p className="text-lg text-slate-600 dark:text-slate-400 mt-4 max-w-2xl mx-auto">
            Your daily digest of trending AI tools and news, updated automatically.
          </p>
        </header>

        {/* 
          Main Content Area
          Renders the daily updates in chronological order.
          Each day is displayed as a collapsible section for better UX.
        */}
        <div className="w-full">
          {sortedDailyUpdates.map((day, index) => (
            <DailyUpdateSection 
              key={index} 
              day={day} 
              initiallyOpen={index === 0} // Only the most recent day is open by default
            />
          ))}
        </div>

        {/* 
          Footer Section
          Contains attribution, links, and disclaimers.
          Important for legal compliance and user information.
        */}
        <footer className="text-center my-16 text-sm">
            <p className="text-slate-500 dark:text-slate-400">
                Maintained by Auto-News AI &copy; {new Date().getFullYear()}
            </p>
             <a 
                href="https://github.com/viraj89/ai-resources-and-tools" 
                target="_blank" 
                rel="noopener noreferrer" 
                className="text-slate-500 hover:text-sky-500 dark:hover:text-sky-400 transition-colors mt-2 block"
             >
                View Source on GitHub
            </a>
            <p className="text-xs text-slate-400 dark:text-slate-500 mt-4 max-w-lg mx-auto">
                Disclaimer: This content is aggregated automatically. Information may be outdated or inaccurate. Please verify all information and use at your own risk.
            </p>
        </footer>
      </div>
    </main>
  );
}