// This file is auto-generated by prepare_website_data.py. Do not edit manually.
// Last generated: 2025-06-21T11:39:43.632602

export const content = {
  "last_updated": "2025-06-21T11:39:43.630342",
  "daily_updates": [
    {
      "date": "2025-06-21T00:00:00",
      "type": "news",
      "title": "AI News for June 21, 2025",
      "data": [
        {
          "title": "AI startups drive VC funding resurgence, capturing record US investment in 2024",
          "url": "https://tinyurl.com/257zjokf",
          "source": "Reuters"
        },
        {
          "title": "Venture capital investment is rising in Los Angeles — and not just for AI startups",
          "url": "https://tinyurl.com/2bhpzdz9",
          "source": "Los Angeles Times"
        },
        {
          "title": "AI Startups Continue to Masquerade as SaaS Businesses; OpenAI Lays Off Some ‘Insider Risk’ Employees",
          "url": "https://tinyurl.com/27s32bgc",
          "source": "The Information"
        },
        {
          "title": "Major VC merger births Northern investment powerhouse- PXN Group with £670M fund",
          "url": "https://tinyurl.com/29l6wvqz",
          "source": "Tech Funding News"
        },
        {
          "title": "Venture Capital Investment in Women's Health Startups Reaching Record Highs; Silicon Valley Bank Releases Report",
          "url": "https://tinyurl.com/2cul9ek5",
          "source": "Silicon Valley Bank"
        },
        {
          "title": "The Senate Republican Budget Bill Adds Broadband Funding That Favors Musk’s Starlink and Bans State AI Laws",
          "url": "https://tinyurl.com/2dk8hr2o",
          "source": "Center for American Progress"
        },
        {
          "title": "Following months of record high AI funding, new Prosus report says applications will drive the next wave of AI investment",
          "url": "https://tinyurl.com/2dzhvdpq",
          "source": "Prosus"
        },
        {
          "title": "OpenAI urges US to prioritize AI funding, regulation to stay ahead of China",
          "url": "https://tinyurl.com/29mk33c7",
          "source": "Reuters"
        },
        {
          "title": "Exclusive | OpenAI and Microsoft Tensions Are Reaching a Boiling Point",
          "url": "https://tinyurl.com/2cpeqdba",
          "source": "WSJ"
        },
        {
          "title": "Exclusive | OpenAI and Microsoft Tensions Are Reaching a Boiling Point",
          "url": "https://tinyurl.com/2asalkou",
          "source": "WSJ"
        }
      ]
    },
    {
      "date": "2025-06-20T00:00:00",
      "type": "tools",
      "title": "AI Tools of the Day: June 20, 2025",
      "data": [
        {
          "name": "Elon Musk calls Grok answer a ‘major fail’ after it highlights political violence caused by MAGA supporters",
          "url": "https://ecency.com/hive-109255/@kur8/elon-musk-calls-grok-answer",
          "description": "Source: Independent Elon Musk criticised his AI chatbot, Grok, after it stated that right-wing political violence in the U.S. has been more ... by @kur8"
        },
        {
          "name": "🧠 How to Visualize a Neural Network (Hint: It’s Not a Straight Line)",
          "url": "https://i.redd.it/wvoahuqcb08f1.jpeg",
          "description": "Most people picture a neural network like this:  Input → Hidden → Output      ● → ● → ●  Clean. Linear. Predictable.  But real neural networks—especially massive transformer models like GPT—don’t thin..."
        },
        {
          "name": "Does anyone know anything about context windows on longer (20-30 second) Wan videos?",
          "url": "https://i.redd.it/keexq04rms7f1.gif",
          "description": "**TLDR:**  **1. From 481 frames with 160 context windows and 4 stride and overlap what would make a video with less visual anomalies (white smudgey halo around character) than we see at 10, 15 and 20 ..."
        },
        {
          "name": "lancedb /lance",
          "url": "https://github.com/lancedb/lance",
          "description": "Modern columnar data format for ML and LLMs implemented in Rust. Convert from parquet in 2 lines of code for 100x faster random access, vector index, and data versioning. Compatible with Pandas, DuckD..."
        },
        {
          "name": "microsoft /playwright",
          "url": "https://github.com/microsoft/playwright",
          "description": "Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.  - GitHub - microsoft/playwright: Playwright is a framework for Web Testing ..."
        }
      ]
    },
    {
      "date": "2025-06-20T00:00:00",
      "type": "news",
      "title": "AI News for June 20, 2025",
      "data": [
        {
          "title": "Exclusive | OpenAI and Microsoft Tensions Are Reaching a Boiling Point",
          "url": "https://tinyurl.com/2bu9mqtg",
          "source": "WSJ"
        },
        {
          "title": "Exclusive: OpenAI taps Google in unprecedented cloud deal despite AI rivalry, sources say",
          "url": "https://tinyurl.com/265jy637",
          "source": "Reuters"
        },
        {
          "title": "Exclusive: Anthropic hits $3 billion in annualized revenue on business demand for AI",
          "url": "https://tinyurl.com/265xzfjg",
          "source": "Reuters"
        },
        {
          "title": "Reddit sues AI startup Anthropic for allegedly using data without permission",
          "url": "https://tinyurl.com/2dzwfupa",
          "source": "Reuters"
        },
        {
          "title": "Exclusive / Anthropic emerges as an adversary to Trump’s big bill",
          "url": "https://tinyurl.com/2yd497hs",
          "source": "Semafor"
        },
        {
          "title": "Anthropic CEO says proposed 10-year ban on state AI regulation 'too blunt' in NYT op-ed",
          "url": "https://tinyurl.com/22zkywoe",
          "source": "Reuters"
        },
        {
          "title": "Anthropic co-founder on cutting access to Windsurf: 'It would be odd for us to sell Claude to OpenAI'",
          "url": "https://tinyurl.com/2ywsycx5",
          "source": "TechCrunch"
        },
        {
          "title": "Exclusive | OpenAI and Microsoft Tensions Are Reaching a Boiling Point",
          "url": "https://tinyurl.com/232scrat",
          "source": "WSJ"
        },
        {
          "title": "Canadian AI start-up Cohere seeks US$500 million in effort to catch up to OpenAI and Anthropic",
          "url": "https://tinyurl.com/26etf5rf",
          "source": "Financial Post"
        },
        {
          "title": "Claude Opus 4 is Anthropic's Powerful, Problematic AI Model",
          "url": "https://tinyurl.com/27zp3ba5",
          "source": "BankInfoSecurity"
        }
      ]
    }
  ],
  "tools_directory": {
    "Text / Chat Assistants": [
      {
        "name": "ChatGPT",
        "url": "https://chat.openai.com",
        "description": "AI chatbot for writing and Q&A",
        "pricing": "Freemium"
      },
      {
        "name": "Claude",
        "url": "https://claude.ai",
        "description": "AI assistant by Anthropic",
        "pricing": "Freemium"
      },
      {
        "name": "Poe",
        "url": "https://poe.com",
        "description": "Hub for chatting with multiple AI models",
        "pricing": "Freemium"
      },
      {
        "name": "huggingface /transformers",
        "url": "https://github.com/huggingface/transformers",
        "description": "🤗 Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.  - GitHub - huggingface/tran...",
        "pricing": "Freemium"
      },
      {
        "name": "🧠 How to Visualize a Neural Network (Hint: It’s Not a Straight Line)",
        "url": "https://i.redd.it/wvoahuqcb08f1.jpeg",
        "description": "Most people picture a neural network like this:\n\nInput → Hidden → Output  \n   ● → ● → ●\n\nClean. Linear. Predictable.\n\nBut real neural networks—especially massive transformer models like GPT—don’t thin...",
        "pricing": "N/A"
      },
      {
        "name": "Does anyone know anything about context windows on longer (20-30 second) Wan videos?",
        "url": "https://i.redd.it/keexq04rms7f1.gif",
        "description": "**TLDR:**\n\n**1. From 481 frames with 160 context windows and 4 stride and overlap what would make a video with less visual anomalies (white smudgey halo around character) than we see at 10, 15 and 20 ...",
        "pricing": "Paid"
      },
      {
        "name": "modelscope /FunASR",
        "url": "https://github.com/modelscope/FunASR",
        "description": "A Fundamental End-to-End Speech Recognition Toolkit and Open Source SOTA Pretrained Models, Supporting Speech Recognition, Voice Activity Detection, Text Post-processing etc. - modelscope/FunASR",
        "pricing": "Freemium"
      },
      {
        "name": "🧠 How to Visualize a Neural Network (Hint: It’s Not a Straight Line)",
        "url": "https://i.redd.it/wvoahuqcb08f1.jpeg",
        "description": "Most people picture a neural network like this:\n\nInput → Hidden → Output  \n   ● → ● → ●\n\nClean. Linear. Predictable.\n\nBut real neural networks—especially massive transformer models like GPT—don’t thin...",
        "pricing": "N/A"
      },
      {
        "name": "Does anyone know anything about context windows on longer (20-30 second) Wan videos?",
        "url": "https://i.redd.it/keexq04rms7f1.gif",
        "description": "**TLDR:**\n\n**1. From 481 frames with 160 context windows and 4 stride and overlap what would make a video with less visual anomalies (white smudgey halo around character) than we see at 10, 15 and 20 ...",
        "pricing": "Paid"
      }
    ],
    "Search / Research": [
      {
        "name": "Perplexity",
        "url": "https://www.perplexity.ai",
        "description": "AI search engine with citations",
        "pricing": "Freemium"
      },
      {
        "name": "mindsdb /mindsdb",
        "url": "https://github.com/mindsdb/mindsdb",
        "description": "AI's query engine - Platform for building AI that can answer questions over large scale federated data. - The only MCP Server you'll ever need - mindsdb/mindsdb",
        "pricing": "Freemium"
      }
    ],
    "Code / Developer Tools": [
      {
        "name": "Cursor",
        "url": "https://www.cursor.so",
        "description": "AI-first code editor",
        "pricing": "Freemium"
      },
      {
        "name": "GitHub Copilot",
        "url": "https://github.com/features/copilot",
        "description": "AI pair programmer in IDE",
        "pricing": "Paid"
      },
      {
        "name": "Loveable",
        "url": "https://lovable.dev",
        "description": "AI that explains and debugs code",
        "pricing": "Freemium"
      },
      {
        "name": "cocos /cocos-engine",
        "url": "https://github.com/cocos/cocos-engine",
        "description": "Cocos simplifies game creation and distribution with Cocos Creator, a free, open-source, cross-platform game engine. Empowering millions of developers to create high-performance, engaging 2D/3D games ...",
        "pricing": "Freemium"
      },
      {
        "name": "windmill-labs /windmill",
        "url": "https://github.com/windmill-labs/windmill",
        "description": "Open-source developer platform to power your entire infra and turn scripts into webhooks, workflows and UIs. Fastest workflow engine (13x vs Airflow). Open-source alternative to Retool and Temporal. -...",
        "pricing": "Freemium"
      },
      {
        "name": "n8n-io /n8n",
        "url": "https://github.com/n8n-io/n8n",
        "description": "Fair-code workflow automation platform with native AI capabilities. Combine visual building with custom code, self-host or cloud, 400+ integrations. - n8n-io/n8n",
        "pricing": "Freemium"
      },
      {
        "name": "Meta in talks to hire former GitHub CEO Nat Friedman as part of AI push – report",
        "url": "https://www.proactiveinvestors.co.uk/companies/news/1073286/meta-in-talks-to-hire-former-github-ceo-nat-friedman-as-part-of-ai-push-report-1073286.html",
        "description": "",
        "pricing": "Paid"
      },
      {
        "name": "lancedb /lance",
        "url": "https://github.com/lancedb/lance",
        "description": "Modern columnar data format for ML and LLMs implemented in Rust. Convert from parquet in 2 lines of code for 100x faster random access, vector index, and data versioning. Compatible with Pandas, DuckD...",
        "pricing": "Freemium"
      },
      {
        "name": "lancedb /lance",
        "url": "https://github.com/lancedb/lance",
        "description": "Modern columnar data format for ML and LLMs implemented in Rust. Convert from parquet in 2 lines of code for 100x faster random access, vector index, and data versioning. Compatible with Pandas, DuckD...",
        "pricing": "Freemium"
      }
    ],
    "Productivity / Writing": [
      {
        "name": "Notion AI",
        "url": "https://www.notion.so/product/ai",
        "description": "AI writing assistant built into Notion",
        "pricing": "Freemium"
      }
    ],
    "Design / Image Generation": [
      {
        "name": "Krea AI",
        "url": "https://www.krea.ai",
        "description": "AI for image generation and editing",
        "pricing": "Freemium"
      },
      {
        "name": "Leonardo AI",
        "url": "https://www.leonardo.ai",
        "description": "AI for game art and image creation",
        "pricing": "Freemium"
      },
      {
        "name": "The Pig in Yellow: Part 2",
        "url": "https://i.redd.it/e4m0oz92808f1.png",
        "description": "**II.**\n&gt; *“His mind is a wonder chamber, from which he can extract treasures that you and I would give years of our life to acquire.”*\n\n**II.i**\n\nA user inputs an idea, a question, a belief.\n\nA sy...",
        "pricing": "Freemium"
      },
      {
        "name": "Is artificial intelligence (AI) smart or just efficient?",
        "url": "https://alpha.leofinance.io/@badbitch/is-artificial-intelligence-ai-smart-or-just-efficient-9wp",
        "description": "I came across a tweet today where an individual talks about how he believes chatGPT is much smarter...",
        "pricing": "N/A"
      },
      {
        "name": "OpenAI",
        "url": "N/A",
        "description": "2. AI Startups Continue to Masquerade as SaaS Businesses; OpenAI Lays Off Some ‘Insider Risk’ Employees - The Information [2]",
        "pricing": "N/A"
      },
      {
        "name": "8 Depth Estimation Models Tested with the Highest Settings on ComfyUI",
        "url": "https://i.redd.it/noifyjoitw7f1.jpeg",
        "description": "I tested all 8 available depth estimation models on ComfyUI on different types of images. I used the largest versions, highest precision and settings available that would fit on 24GB VRAM. \n\nThe model...",
        "pricing": "Paid"
      },
      {
        "name": "Wan 2.1 I2V 14B 480p - my first video stitching test",
        "url": "https://v.redd.it/xz4nn241uu7f1",
        "description": "Simple movements, I know, but I was pleasantly surprised by how well it fits together for my first try. I'm sure my workflows have lots of room for optimization - altogether this took nearly 20 minute...",
        "pricing": "Paid"
      },
      {
        "name": "Enter the Swamp",
        "url": "https://i.redd.it/6z4otjjnlx7f1.png",
        "description": "Prompt:\n```\nA haunted, mist-shrouded swamp at twilight, with twisted, moss-covered trees, eerie will-o'-the-wisps hovering over stagnant water, and the ruins of a sunken chapel half-submerged in mud, ...",
        "pricing": "Paid"
      },
      {
        "name": "Quick tip for anyone generating videos with Hailuo 2 or Midjourney Video since they don't generate with any sound. You can generate sound effects for free using MMAUDIO via huggingface.",
        "url": "https://v.redd.it/v4k33g4u908f1",
        "description": "",
        "pricing": "Freemium"
      },
      {
        "name": "Hips don't lie",
        "url": "https://v.redd.it/k7a2s06wwy7f1",
        "description": "I made this video by stitching together two 7-second clips made with FusionX (Q8 GGUF model). Each little 7-second clip took about 10 minutes to render on RTX 3090. Base image made with FLUX Dev\n\nIt w...",
        "pricing": "N/A"
      }
    ],
    "Video / Creative Tools": [
      {
        "name": "Runway ML",
        "url": "https://runwayml.com",
        "description": "AI video editing and creative tools",
        "pricing": "Paid"
      },
      {
        "name": "HeyGen",
        "url": "https://www.heygen.com",
        "description": "AI avatar-based video creation",
        "pricing": "Paid"
      },
      {
        "name": "Veo 3",
        "url": "https://veo.google",
        "description": "Google's experimental video generation model",
        "pricing": "N/A 17"
      },
      {
        "name": "YouTube CEO announces Google's Veo 3 AI video tech is coming to Shorts",
        "url": "https://www.pcguide.com/news/youtube-ceo-announces-googles-veo-3-ai-video-tech-is-coming-to-shorts/",
        "description": "At the Cannes Lions 2025 International Festival of Creativity, Neal Mohan discusses 20 years of YouTube and what's next for the platform.",
        "pricing": "N/A"
      },
      {
        "name": "WAN2.1 Why all my clowns look so scary? Any tips to make him look more friendly?",
        "url": "https://v.redd.it/86v1ceynsy7f1",
        "description": "The prompt is always \"a man wearing a yellow and red clown costume.\" but he looks straight out of a horror movie",
        "pricing": "Paid"
      }
    ],
    "Voice / Audio Tools": [
      {
        "name": "ElevenLabs",
        "url": "https://www.elevenlabs.io",
        "description": "AI voice cloning and text-to-speech",
        "pricing": "Freemium"
      }
    ],
    "Presentations": [
      {
        "name": "Gamma",
        "url": "https://gamma.app",
        "description": "AI-generated presentation builder",
        "pricing": "Freemium"
      },
      {
        "name": "Tome",
        "url": "https://tome.app",
        "description": "AI tool for storytelling and slides",
        "pricing": "Freemium"
      }
    ],
    "Other": [
      {
        "name": "automatisch /automatisch",
        "url": "https://github.com/automatisch/automatisch",
        "description": "The open source Zapier alternative. Build workflow automation without spending time and money. - automatisch/automatisch",
        "pricing": "Freemium"
      },
      {
        "name": "PaperMC /Paper",
        "url": "https://github.com/PaperMC/Paper",
        "description": "The most widely used, high performance Minecraft server that aims to fix gameplay and mechanics inconsistencies - PaperMC/Paper",
        "pricing": "Freemium"
      },
      {
        "name": "microsoft /onnxruntime",
        "url": "https://github.com/microsoft/onnxruntime",
        "description": "ONNX Runtime: cross-platform, high performance ML inferencing and training accelerator - microsoft/onnxruntime",
        "pricing": "Freemium"
      },
      {
        "name": "[R] Reasoning by Superposition: A Theoretical Perspective on Chain of Continuous Thought",
        "url": "https://arxiv.org/pdf/2505.12514",
        "description": "",
        "pricing": "N/A"
      },
      {
        "name": "OpenAI's Greg Brockman expects AIs to go from AI coworkers to AI managers: \"the AI gives you ideas and gives you tasks to do\"",
        "url": "https://v.redd.it/ssf04g7dnw7f1",
        "description": "",
        "pricing": "N/A"
      },
      {
        "name": "Quick Daily AI",
        "url": "N/A",
        "description": "## Quick Daily AI News June 20, 2025",
        "pricing": "N/A"
      },
      {
        "name": "Bank of America shrinks workforce by leveraging AI",
        "url": "N/A",
        "description": "3. Bank of America shrinks workforce by leveraging AI, tech investments to boost efficiency - The Business Journals [3]",
        "pricing": "N/A"
      },
      {
        "name": "Starlink and Bans State AI",
        "url": "N/A",
        "description": "6. The Senate Republican Budget Bill Adds Broadband Funding That Favors Musk’s Starlink and Bans State AI Laws - Center for American Progress [6]",
        "pricing": "Paid"
      },
      {
        "name": "Following months of record high AI",
        "url": "N/A",
        "description": "7. Following months of record high AI funding, new Prosus report says applications will drive the next wave of AI investment - Prosus [7]",
        "pricing": "Paid"
      },
      {
        "name": "Prosus report says applications will drive the next wave of AI",
        "url": "N/A",
        "description": "7. Following months of record high AI funding, new Prosus report says applications will drive the next wave of AI investment - Prosus [7]",
        "pricing": "Paid"
      },
      {
        "name": "OpenAI urges US to prioritize AI",
        "url": "N/A",
        "description": "8. OpenAI urges US to prioritize AI funding, regulation to stay ahead of China - Reuters [8]",
        "pricing": "N/A"
      },
      {
        "name": "Tesla CEO Elon Musk calls OpenAI",
        "url": "N/A",
        "description": "10. Here's what made Tesla CEO Elon Musk calls OpenAI CEO as SCAM Altman - Times of India [10]",
        "pricing": "N/A"
      },
      {
        "name": "dail8859 /NotepadNext",
        "url": "https://github.com/dail8859/NotepadNext",
        "description": "A cross-platform, reimplementation of Notepad++. Contribute to dail8859/NotepadNext development by creating an account on GitHub.",
        "pricing": "Freemium"
      },
      {
        "name": "Elon Musk calls Grok answer a ‘major fail’ after it highlights political violence caused by MAGA supporters",
        "url": "https://ecency.com/hive-109255/@kur8/elon-musk-calls-grok-answer",
        "description": "Source: Independent Elon Musk criticised his AI chatbot, Grok, after it stated that right-wing political violence in the U.S. has been more ... by @kur8",
        "pricing": "N/A"
      },
      {
        "name": "microsoft /playwright",
        "url": "https://github.com/microsoft/playwright",
        "description": "Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.  - GitHub - microsoft/playwright: Playwright is a framework for Web Testing ...",
        "pricing": "Freemium"
      },
      {
        "name": "Replacing Everyone with AI",
        "url": "https://youtu.be/THfBccihkVQ",
        "description": "*Our first longform animation is finally here!*Toxic CEO is back! This time, he's got a genius plan to boost productivity: fire everyone and replace the offi...",
        "pricing": "N/A"
      },
      {
        "name": "\"We find that AI models can accurately guide users through the recovery of live poliovirus.\"",
        "url": "https://i.redd.it/8fn2mhf4qp7f1.png",
        "description": "[https://arxiv.org/abs/2506.13798](https://arxiv.org/abs/2506.13798)",
        "pricing": "N/A"
      },
      {
        "name": "The OpenAI Files: a comprehensive and concerning look at the inner workings of the leading AI lab",
        "url": "https://www.openaifiles.org",
        "description": "The OpenAI Files is the most comprehensive collection to date of documented concerns with governance practices, leadership integrity, and organizational culture at OpenAI.",
        "pricing": "N/A"
      },
      {
        "name": "Elon Musk calls Grok answer a ‘major fail’ after it highlights political violence caused by MAGA supporters",
        "url": "https://ecency.com/hive-109255/@kur8/elon-musk-calls-grok-answer",
        "description": "Source: Independent Elon Musk criticised his AI chatbot, Grok, after it stated that right-wing political violence in the U.S. has been more ... by @kur8",
        "pricing": "N/A"
      },
      {
        "name": "microsoft /playwright",
        "url": "https://github.com/microsoft/playwright",
        "description": "Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.  - GitHub - microsoft/playwright: Playwright is a framework for Web Testing ...",
        "pricing": "Freemium"
      }
    ],
    "https://www.reuters.com/world/us/openai-wins-200-million-us-defense-contract-2025-06-16/?utm_source=chatgpt.com": [
      {
        "name": "Code / Developer Tools",
        "url": "OpenAI and Palantir have both been involved in U.S. Department of Defense initiatives. In June 2025, senior executives from both firms (OpenAI’s Chief Product Officer Kevin Weil and Palantir CTO Shyam...",
        "description": "Paid",
        "pricing": "182.7"
      },
      {
        "name": "Code / Developer Tools",
        "url": "OpenAI and Palantir have both been involved in U.S. Department of Defense initiatives. In June 2025, senior executives from both firms (OpenAI’s Chief Product Officer Kevin Weil and Palantir CTO Shyam...",
        "description": "Paid",
        "pricing": "182.6"
      }
    ],
    "https://venturebeat.com/programming-development/openai-open-sourced-a-new-customer-service-agent-framework-learn-more-about-its-growing-enterprise-strategy/": [
      {
        "name": "Code / Developer Tools",
        "url": "By offering transparent tooling and clear implementation examples, OpenAI is pushing agentic systems out of the lab and into everyday use.",
        "description": "Freemium",
        "pricing": "120"
      }
    ],
    "https://huggingface.co/mistralai/Mistral-Small-3.2-24B-Instruct-2506": [
      {
        "name": "Other",
        "url": "We’re on a journey to advance and democratize artificial intelligence through open source and open science.",
        "description": "Paid",
        "pricing": "106.4"
      },
      {
        "name": "Other",
        "url": "We’re on a journey to advance and democratize artificial intelligence through open source and open science.",
        "description": "Paid",
        "pricing": "106.2"
      }
    ]
  }
};
