name: Daily AI News Update

on:
  schedule:
    # Runs at 7 AM IST (1:30 UTC)
    - cron: '30 1 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run news update
      run: |
        python tools/script/update_blogs_and_news.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add tools/blogs-and-news.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily AI news [skip ci]" && git push) 