name: Daily Update - Tools, News, and Website

on:
  schedule:
    # Runs daily at 7:30 AM IST (2:00 UTC)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  daily-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # Cache dependencies
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run daily tools digest
      id: daily_tools
      run: daily-tools

    - name: Run news update
      id: news_update
      run: update-news

    - name: Generate tools directory
      id: tools_directory
      run: tools-directory
      
    - name: Prepare website data
      id: prepare_data
      run: prepare-website-data

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        # Check for changes and commit if any
        if ! git diff --staged --quiet; then
          git commit -m "feat: Daily update of tools, news, and website data" -m "Automated by GitHub Actions - $(date)"
          git push
        else
          echo "No changes to commit."
        fi 